# GeyserDebugInfo Configuration File
# A Geyser extension that strives to provide F3-like debug information for Bedrock Edition players.
#
# Report any issues on our GitHub repository:
# https://github.com/RealTriassic/GeyserDebugInfo

display:
  bossbar:
    text:
      - "Geyser Debug Information"
      - ""
      - "%player_world%"
      - ""
      - "XYZ: %player_x% / %player_y% / %player_z%"
      - "Block: %player_x:floor% %player_y:floor% %player_z:floor% [%player_relative_x% %player_relative_y% %player_relative_z%]"
      - "Chunk: %player_chunk_x% %player_chunk_y% %player_chunk_z% [%player_global_x% %player_global_z% in %player_region_file%]"
      - "Facing: %player_facing% (%player_yaw% / %player_pitch%)"

config-version: 1