metadata.format.version = "1.1"

[versions]
configurate = "4.1.2"
geyser = "2.4.2-SNAPSHOT"
shadow = "8.3.2"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
configurate-hocon = { group = "org.spongepowered", name = "configurate-hocon", version.ref = "configurate" }
geyser-core = { group = "org.geysermc.geyser", name = "core", version.ref = "geyser" }