[versions]
configurate = "4.1.2"
geyser = "2.4.3-SNAPSHOT"
shadow = "8.3.3"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
configurate-yaml = { group = "org.spongepowered", name = "configurate-yaml", version.ref = "configurate" }
geyser-core = { group = "org.geysermc.geyser", name = "core", version.ref = "geyser" }